# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a453f7418d5ff9a79a68baea8a83c6af136b4eb5481b1f0f2e81fc2b84d8abd6a5d73e05f856e4e06e2c5bcaf67204c04612c3d6615d4681806f8f3004802892

test:
  secret_key_base: 2faebfdd3de744e16b1e80b53392ed42ee6000510d22497bb4cd73e35e3246441122c7ecff929ed80af30bd4b33c5cfe2f8bc97a4535168ec8a997d87d460654

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
